### ISSUE TITLE
/dev/console Permission denied

### ISSUE THREAD

**Issue by charlesfracchia** [textmate/git.tmbundle#35]
Unsure what I did (or what happened) that broke my Git integration but I now get a: ```sh: /dev/console: Permission denied``` when I try to make a commit. I don't exclude this being my fault but I tried everything to fix it, and have already done the following (to no avail):
- uninstalled / reinstalled Git bundle
- uninstalled / reinstalled TM command line tools
- uninstalled / reinstalled Git on my system (using brew)

Note that this error doesn't occur when the directory is clean (because I've committed using command line) and the interface shows the correct message (that the directory is clean).

I'm using version 2.0-beta.7.1 of TextMate

Any idea what may be causing this?

**Comment by sorbits** [comment]
Try run `echo foo > /dev/console` in a terminal.

If it gives the same error, try reboot your machine.

**Comment by charlesfracchia** [comment]
Thanks a lot. Rebooting did the trick.
Still not sure what happened but thanks for the help.
