### ISSUE TITLE
The commit option

### ISSUE THREAD

**Issue by baldwind** [textmate/git.tmbundle#43]
The commit option only commits the selected file and not all the files added to the index. The functionality either needs to be changed or a second option added that does a $ git commit -m 'hello world'
committing all indexed files to the repo.

**Comment by arimbun** [comment]
I believe you can commit all files by not selecting any file during the commit.

**Comment by sorbits** [comment]
As @arimbun says, if you do not select any files (in the file browser) when invoking the commit action then all files will be selected for commit (but you can filter that in the commit dialog that appears).

FYI pressing <kbd>⇧⌘A</kbd> is a shortcut to deselect everything in the file browser.

I do not think we need another commit action that commits the index “as is”, as if you’re using `git add …` from the terminal then there is really no reason not to also use `git commit …` once you have added the desired changes.
