### ISSUE TITLE
Git push not working

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [textmate/git.tmbundle#56]
Hi,
I'm having trouble getting TextMate to work with [Netlify Git's credential helper](https://github.com/netlify/netlify-credential-helper). After installing `netlify-credential-helper` I get this error in TextMate:
![image](https://user-images.githubusercontent.com/9049533/89897513-69f3d980-dbdf-11ea-8f73-975e60951860.png)

I can `git push` from my Terminal just fine. My `git config -l` looks like this:
```
credential.helper=osxkeychain
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.name=rodrigoalcarazdelaosa
user.email=rodri.alcaraz@gmail.com
git-tmbundle.gitnub-path=https://github.com/rodrigoalcarazdelaosa
credential.helper=osxkeychain
include.path=/Users/rodrigoalcarazdelaosa/.netlify/helper/git-config
credential.helper=
credential.helper=netlify
credential.helper=osxkeychain
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=https://github.com/rodrigoalcarazdelaosa/rodrigoalcarazdelaosa.me.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.https://084c644c-1539-4d00-93bc-dc75f576de30.netlify.app/.netlify/large-media.access=basic
lfs.https://084c644c-1539-4d00-93bc-dc75f576de30.netlify.app/.netlify/large-media.locksverify=false
```
As you can see, I'm using two different credential helpers (`netlify` and `osxkeychain`) but after the line:
```
git-tmbundle.gitnub-path=https://github.com/rodrigoalcarazdelaosa
```
I only have `credential.helper=osxkeychain` which may be the source of this issue but I have no idea really.

Can anyone help me?
Thanks in advance!

**Comment by sorbits** [comment]
Try set `PATH` in TextMate → Preferences → Variables so that it matches your terminal.

For further support see https://macromates.com/support

**Comment by rodrigoalcarazdelaosa** [comment]
> Try set `PATH` in TextMate → Preferences → Variables so that it matches your terminal.

This did the trick, thank you very much!
